server:
  port: 8083

spring:
  application:
    name: sc-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: service-feign
          uri: lb://SERVICE-FEIGN
          predicates:
            - Path=/holiday/**
          filters:
            - StripPrefix=1
            - RequestTime=true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug